apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-container
          image: alpine/openssl
          command:
            - "sh"
            - "-c"
          args:
            - |
              openssl genpkey -algorithm ed25519 -out /keys/ed25519.pem
              openssl pkey -in /keys/ed25519.pem -pubout -out /keys/ed25519.pem.pub

              touch /app/application.properties
              echo "private.key=/app/keys/ed25519.pem" >> /app/application.properties
              echo "public.key=/app/keys/ed25519.pem.pub" >> /app/application.properties
              echo "host.name=${HOST_NAME}" >> /app/application.properties
              echo "logging.level.root=${LOG_LEVEL}" >> /app/application.properties
          env:
            - name: HOST_NAME
              value: {{ .Values.app.host | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.app.logging.level | quote }}
          volumeMounts:
            - name: application-properties
              mountPath: /app
            - name: application-keys
              mountPath: /keys
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.well-known/did.json
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /.well-known/did.json
              port: http
            initialDelaySeconds: 30
          volumeMounts:
            - name: application-properties
              mountPath: /app/application.properties
              readOnly: true
              subPath: application.properties
            - name: application-keys
              mountPath: /app/keys
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: application-properties
          emptyDir:
            medium: Memory
        - name: application-keys
          emptyDir:
            medium: Memory
