---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connector.fullname" . }}-controlplane
  labels:
    {{- include "connector.controlplane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.controlplane.autoscaling.enabled }}
  replicas: {{ .Values.controlplane.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "connector.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controlplane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "connector.controlplane.selectorLabels" . | nindent 8 }}
        {{- with .Values.controlplane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controlplane.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.controlplane.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controlplane.securityContext | nindent 12 }}
          image: "{{ .Values.controlplane.image.repository }}:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controlplane.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.controlplane.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.controlplane.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.controlplane.endpoints.default.path }}/check/liveness
              port: {{ .Values.controlplane.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.controlplane.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controlplane.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controlplane.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.controlplane.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.controlplane.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.controlplane.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.controlplane.endpoints.default.path }}/check/readiness
              port: {{ .Values.controlplane.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.controlplane.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.controlplane.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.controlplane.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.controlplane.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.controlplane.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.controlplane.resources | nindent 12 }}
          env:
          {{- if .Values.controlplane.debug.enabled }}
            - name: "JAVA_TOOL_OPTIONS"
              value: >-
            {{- if .Values.controlplane.debug.suspendOnStart }}
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=%v" .Values.controlplane.debug.port }}
            {{- else }}
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=%v" .Values.controlplane.debug.port }}
            {{- end }}
          {{- end }}

            #######
            # API #
            #######
            - name: "EDC_API_AUTH_KEY"
              value: {{ .Values.controlplane.endpoints.data.authKey | required ".Values.controlplane.endpoints.data.authKey is required" | quote }}
            - name: "WEB_HTTP_DEFAULT_PORT"
              value: {{ .Values.controlplane.endpoints.default.port | quote }}
            - name: "WEB_HTTP_DEFAULT_PATH"
              value: {{ .Values.controlplane.endpoints.default.path | quote }}
            - name: "WEB_HTTP_MANAGEMENT_PORT"
              value: {{ .Values.controlplane.endpoints.data.port | quote }}
            - name: "WEB_HTTP_MANAGEMENT_PATH"
              value: {{ .Values.controlplane.endpoints.data.path | quote }}
            {{- if or (eq (substr 0 3 .Values.controlplane.image.tag) "0.1") (eq (substr 0 3 .Values.controlplane.image.tag) "0.2") }}
            # WEB_HTTP_DATA_PORT is renamed to WEB_HTTP_MANAGEMENT_PORT from version 0.2.1 and newer
            # we will keep both settings for downward capabilities
            - name: "WEB_HTTP_DATA_PORT"
              value: {{ .Values.controlplane.endpoints.data.port | quote }}
            # WEB_HTTP_DATA_PATH is renamed to WEB_HTTP_MANAGEMENT_PATH from version 0.2.1 and newer
            # we will keep both settings for downward capabilities
            - name: "WEB_HTTP_DATA_PATH"
              value: {{ .Values.controlplane.endpoints.data.path | quote }}
            {{- end }}
            - name: "WEB_HTTP_VALIDATION_PORT"
              value: {{ .Values.controlplane.endpoints.validation.port | quote }}
            - name: "WEB_HTTP_VALIDATION_PATH"
              value: {{ .Values.controlplane.endpoints.validation.path | quote }}
            - name: "WEB_HTTP_CONTROL_PORT"
              value: {{ .Values.controlplane.endpoints.control.port | quote }}
            - name: "WEB_HTTP_CONTROL_PATH"
              value: {{ .Values.controlplane.endpoints.control.path | quote }}
            - name: "WEB_HTTP_IDS_PORT"
              value: {{ .Values.controlplane.endpoints.ids.port | quote }}
            - name: "WEB_HTTP_IDS_PATH"
              value: {{ .Values.controlplane.endpoints.ids.path | quote }}
            - name: "WEB_HTTP_WELLKNOWN_PORT"
              value: {{ .Values.controlplane.endpoints.wellknown.port | quote }}
            - name: "WEB_HTTP_WELLKNOWN_PATH"
              value: {{ .Values.controlplane.endpoints.wellknown.path | quote }}
            - name: "WEB_HTTP_SSI_PORT"
              value: {{ .Values.controlplane.endpoints.ssi.port | quote }}
            - name: "WEB_HTTP_SSI_PATH"
              value: {{ .Values.controlplane.endpoints.ssi.path | quote }}

            #######
            # SSI #
            #######

            - name: "EDC_SSI_DATASPACE_OPERATOR"
              value: {{ .Values.ssi.dataspace.operator | quote }}

            {{- with  .Values.ssi.agent.embedded}}
            - name: "EDC_SSI_AGENT"
              value: "embedded"
            - name: "EDC_SSI_AGENT_EMBEDDED_HOST_NAME"
              value: {{ .hostname | required "hostname is required" | quote }}
            - name: "EDC_SSI_AGENT_EMBEDDED_SIGNING_PRIVATE_KEY_ALIAS"
              value: {{ .signingKey.privateKeyVaultAlias | quote }}
            - name: "EDC_SSI_AGENT_EMBEDDED_SIGNING_PUBLIC_KEY_ALIAS"
              value: {{ .signingKey.publicKeyVaultAlias | quote }}
            - name: "EDC_SSI_AGENT_EMBEDDED_DID_WEB_RESOLVE_ENFORCE_HTTPS"
              value: {{ .enforceHttpsToResolveDidWeb | quote }}
            {{- end }}

            #########
            ## IDS ##
            #########
            - name: "IDS_WEBHOOK_ADDRESS"
              value: {{ include "connector.controlplane.url.ids" . | quote }}
            - name: "EDC_IDS_ENDPOINT"
              value: {{ printf "%s%s" (include "connector.controlplane.url.ids" .) .Values.controlplane.endpoints.ids.path | quote }}
            - name: "EDC_IDS_ID"
              value: {{ printf "urn:connector:%s" (lower .Values.controlplane.internationalDataSpaces.id) | quote }}
            - name: "EDC_IDS_DESCRIPTION"
              value: {{ .Values.controlplane.internationalDataSpaces.description | quote }}
            - name: "EDC_IDS_TITLE"
              value: {{ .Values.controlplane.internationalDataSpaces.title | quote }}
            - name: "EDC_IDS_MAINTAINER"
              value: {{ .Values.controlplane.internationalDataSpaces.maintainer | quote }}
            - name: "EDC_IDS_CURATOR"
              value: {{ .Values.controlplane.internationalDataSpaces.curator | quote }}
            - name: "EDC_IDS_CATALOG_ID"
              value: {{ printf "urn:catalog:%s" (lower .Values.controlplane.internationalDataSpaces.catalogId) | quote }}
            - name: "EDC_OAUTH_PROVIDER_AUDIENCE"
              value: "idsc:IDS_CONNECTORS_ALL"
            - name: "EDC_OAUTH_ENDPOINT_AUDIENCE"
              value: {{ printf "%s%s%s" (include "connector.controlplane.url.ids" . ) .Values.controlplane.endpoints.ids.path "/data" | quote }}
            # this is the old setting name for 'EDC_OAUTH_ENDPOINT_AUDIENCE' and is mandatory for Produce EDC v0.1.2 and older
            - name: "EDC_IDS_ENDPOINT_AUDIENCE"
              value: {{ printf "%s%s%s" (include "connector.controlplane.url.ids" . ) .Values.controlplane.endpoints.ids.path "/data" | quote }}

            ################
            ## DATA PLANE ##
            ################

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/dataplane-selector-configuration
            - name: "EDC_DATAPLANE_SELECTOR_DEFAULTPLANE_URL"
              value: {{ include "connector.dataplane.url.control" . }}/transfer
            - name: "EDC_DATAPLANE_SELECTOR_DEFAULTPLANE_SOURCETYPES"
              value: "HttpData,AmazonS3"
            - name: "EDC_DATAPLANE_SELECTOR_DEFAULTPLANE_DESTINATIONTYPES"
              value: "HttpProxy,AmazonS3"
            - name: "EDC_DATAPLANE_SELECTOR_DEFAULTPLANE_PROPERTIES"
              value: |-
                {{ printf "{ \"publicApiUrl\": \"%s/\" }" (include "connector.dataplane.url.public" . ) }}

            # see extension https://github.com/eclipse-edc/Connector/tree/main/extensions/control-plane/data-plane-transfer
            - name: "EDC_TRANSFER_PROXY_ENDPOINT"
              value: {{ include "connector.dataplane.url.public" . }}/
            - name: "EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS"
              value: {{ .Values.vault.secretNames.transferProxyTokenSignerPrivateKey | quote }}
            - name: "EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS"
              value: {{ .Values.vault.secretNames.transferProxyTokenSignerPublicKey | quote }}

            # see extension https://github.com/eclipse-edc/Connector/tree/main/extensions/control-plane/http-receiver

            - name: "EDC_RECEIVER_HTTP_ENDPOINT"
              value: {{ .Values.backendService.httpProxyTokenReceiverUrl | required ".Values.backendService.httpProxyTokenReceiverUrl is required" | quote }}

            ###########
            ## VAULT ##
            ###########

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/hashicorp-vault
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ .Values.vault.hashicorp.url | required ".Values.vault.hashicorp.url is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              value: {{ .Values.vault.hashicorp.token | required ".Values.vault.hashicorp.token is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ .Values.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ .Values.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ .Values.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ .Values.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ .Values.vault.hashicorp.paths.health | quote }}

            #####################
            ## DATA ENCRYPTION ##
            #####################

            # see extension https://github.com/catenax-ng/product-edc/tree/develop/edc-extensions/data-encryption
            - name: "EDC_DATA_ENCRYPTION_KEYS_ALIAS"
              value: {{ .Values.vault.secretNames.transferProxyTokenEncryptionAesKey | quote }}
            - name: "EDC_DATA_ENCRYPTION_ALGORITHM"
              value: "AES"

            ######################################
            ## Additional environment variables ##
            ######################################
          {{- range $key, $value := .Values.controlplane.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.controlplane.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.controlplane.envSecretNames .Values.controlplane.envConfigMapNames) (or (gt (len .Values.controlplane.envSecretNames) 0) (gt (len .Values.controlplane.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.controlplane.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.controlplane.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: "configuration"
              mountPath: "/app/opentelemetry.properties"
              subPath: "opentelemetry.properties"
            - name: "configuration"
              mountPath: "/app/logging.properties"
              subPath: "logging.properties"
      volumes:
        - name: "configuration"
          configMap:
            name: {{ include "connector.fullname" . }}-controlplane
            items:
              - key: "opentelemetry.properties"
                path: "opentelemetry.properties"
              - key: "logging.properties"
                path: "logging.properties"
      {{- with .Values.controlplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
